name: squish_them_all
description: A 2d platformer

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flame: ^1.2.1
  flame_forge2d: ^0.12.1
  flame_tiled: ^1.6.0
  tiled: ^0.8.3
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flame_audio: ^1.3.2
  firebase_core: ^2.3.0
  firebase_database: ^10.0.6
  firebase_app_check: ^0.1.1+5
  firebase_analytics: ^10.0.6
  firebase_crashlytics: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/tiles/
    - assets/audio/
