// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVilsQ38lZ_91DrkHoWdSw8qNVkQ5oy70',
    appId: '1:486430935548:web:cc9745ad4c1d1efae0ca79',
    messagingSenderId: '486430935548',
    projectId: 'squishthemall-5c54e',
    authDomain: 'squishthemall-5c54e.firebaseapp.com',
    databaseURL: 'https://squishthemall-5c54e-default-rtdb.firebaseio.com',
    storageBucket: 'squishthemall-5c54e.appspot.com',
    measurementId: 'G-PNSFQTTSCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQbofcBxC-LwmlJ1Wr_93MisR1fml9SVY',
    appId: '1:486430935548:android:5b47bcc333ad015ee0ca79',
    messagingSenderId: '486430935548',
    projectId: 'squishthemall-5c54e',
    databaseURL: 'https://squishthemall-5c54e-default-rtdb.firebaseio.com',
    storageBucket: 'squishthemall-5c54e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2I_uuTNf8jc4HuBjN-0lhqWX7YUh_F5I',
    appId: '1:486430935548:ios:5613ebbc3b11970fe0ca79',
    messagingSenderId: '486430935548',
    projectId: 'squishthemall-5c54e',
    databaseURL: 'https://squishthemall-5c54e-default-rtdb.firebaseio.com',
    storageBucket: 'squishthemall-5c54e.appspot.com',
    iosClientId: '486430935548-c5idjjcdfq3okb4b8n3s1gt32ig389ju.apps.googleusercontent.com',
    iosBundleId: 'com.example.squishThemAll',
  );
}
